;;; Compiled snippets and support files for `+web-react-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets '+web-react-mode
                     '(("ts" "this.state." "this.state" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ts" nil nil)
                       ("tr" "this.refs.\n" "this.refs" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/tr" nil nil)
                       ("tp" "this.props." "this.props" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/tp" nil nil)
                       ("ss" "this.setState({$0})" "React#setState" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ss" nil nil)
                       ("sp" "this.setProps({$0});\n" "React#setProps" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/sp" nil nil)
                       ("scu" "shouldComponentUpdate(${1:nextProps}, ${2:nextState}) {\n  $0\n}\n" "React#shouldComponentUpdate" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/scu" nil nil)
                       ("rr" "React.render(\n  $1,\n  $0\n);\n" "React.render" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/rr" nil nil)
                       ("r" "render() {\n  $0\n}\n" "React#render" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/r" nil nil)
                       ("ptsr" "PropTypes.string.isRequired$0" "create-react-prop-type-string-required" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptsr" nil nil)
                       ("ptoot" "PropTypes.oneOfType([$0]),\n" "create-react-prop-type-oneOfType" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptsh" nil nil)
                       ("pts" "PropTypes.string$0" "create-react-prop-type-string" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/pts" nil nil)
                       ("ptor" "PropTypes.object.isRequired$0," "create-react-prop-type-object-required" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptor" nil nil)
                       ("ptsh" "PropTypes.shape({$0})\n" "create-react-prop-type-shape" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptoot" nil nil)
                       ("ptoo" "PropTypes.oneOf([$0]),\n" "create-react-prop-type-oneOf" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptoo" nil nil)
                       ("pto" "PropTypes.object$0\n" "create-react-prop-type-object" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/pto" nil nil)
                       ("ptnr" "PropTypes.number.isRequired$0" "create-react-prop-type-number-required" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptnr" nil nil)
                       ("ptn" "PropTypes.number$0\n" "create-react-prop-type-number" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptn" nil nil)
                       ("ptfr" "PropTypes.func.isRequired$0" "create-react-prop-type-function-required" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptfr" nil nil)
                       ("ptf" "PropTypes.func$0\n" "create-react-prop-type-function" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptf" nil nil)
                       ("ptbr" "PropTypes.bool.isRequired$0" "create-react-prop-type-bool-required" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptbr" nil nil)
                       ("ptb" "PropTypes.bool$0\n" "create-react-prop-type-bool" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptb" nil nil)
                       ("ptar" "PropTypes.array.isRequired$0" "create-react-prop-type-array-required" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ptar" nil nil)
                       ("pta" "PropTypes.array$0\n" "create-react-prop-type-array" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/pta" nil nil)
                       ("ipr" "import React from 'react'" "import-react" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ipr" nil nil)
                       ("gis" "getInitialState() {\n  $0\n}\n" "React#getInitialState" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/gis" nil nil)
                       ("gdp" "getDefaultProps() {\n  $0\n}\n" "React#getDefaultProps" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/gdp" nil nil)
                       ("cwum" "componentWillUnmount() {\n  $0\n}\n" "React#componentWillUnmount" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/cwum" nil nil)
                       ("cwu" "componentWillUpdate(${1:nextProps}, ${2:nextState}) {\n  $0\n}\n" "React#componentWillUpdate" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/cwu" nil nil)
                       ("cwrp" "componentWillReceiveProps(${1:nextProps}) {\n  $0\n}\n" "React#componentWillReceiveProps" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/cwrp" nil nil)
                       ("cwm" "componentWillMount() {\n  $0\n}\n" "React#componentWillMount" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/cwm" nil nil)
                       ("cdu" "componentDidUpdate(${1:prevProps}, ${2:prevState}, ${3:rootNode}) {\n  $0\n}\n" "React#componentDidUpdate" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/cdu" nil nil)
                       ("cdm" "componentDidMount(${1:rootNode}) {\n  $0\n}\n" "React#componentDidMount" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/cdm" nil nil)
                       ("ccf" "const ${1:MyComponent} = (${2:props}) => {\n  return ${0:null}\n}\n" "create-react-function-class" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ccf" nil nil)
                       ("ccc" "class ${1:MyComponent} extends React.Component {\n  constructor(props) {\n    super(props);\n    this.state={};\n  }\n  render() {\n    return ${0:null};\n  }\n}\n" "React.createClassWithConstructor" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/ccc" nil nil)
                       ("cc" "class ${1:MyComponent} extends React.Component {\n  render() {\n    return ${0:null};\n  }\n}\n" "React.createClass" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/cc" nil nil)
                       ("c" "constructor(props) {\n  super(props);\n  this.state = {$0};\n}\n" "constructor" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/c" nil nil)
                       ("()" "($1) => $0\n" "anonymous_function" nil nil nil "/Users/brandon/.config/doom/snippets/+web-react-mode/()" nil nil)))


;;; Do not edit! File generated at Fri May 11 15:58:26 2018
